name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Generate AniList metrics
        uses: lowlighter/metrics@latest
        with:
          filename: anilist-metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          config_timezone: Europe/Moscow
          config_theme: dark
          plugin_anilist: yes
          plugin_anilist_user: Spinty
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, characters
          plugin_anilist_limit: 2
